name: 'Infracost Run'
description: 'Download Terraform plan artifact and run Infracost to generate cost breakdown.'

inputs:
  artifact-name:
    description: 'Name of the uploaded Terraform plan artifact'
    required: true
    default: 'terraform-plan'
  terraform-plan-file:
    description: 'Path to the Terraform binary plan file inside the artifact'
    required: true
    default: 'tfplan.out'
  working-directory:
    description: 'Directory where Terraform code is located'
    required: false
    default: '.'
  infracost-api-key:
    description: 'Infracost API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download Terraform plan artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: plan-artifact

    - name: Setup Infracost
      uses: infracost/actions/setup@v2

    - name: Convert Terraform plan to JSON
      run: |
        cd plan-artifact
        terraform show -json ${{ inputs.terraform-plan-file }} > plan.json
        echo "----------- Terraform plan converted to JSON -----------"
        cat plan.json
        echo "---------------------------------------------------------"
      shell: bash

    - name: Run Infracost breakdown
      run: |
        infracost breakdown \
          --path=plan-artifact/plan.json \
          --format=table \
          --show-skipped \
          --log-level=info
      shell: bash
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}